// Copyright 2026 RiskEngine Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: decision.proto

package riskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED   Decision = 0
	Decision_DECISION_PASS          Decision = 1
	Decision_DECISION_REJECT        Decision = 2
	Decision_DECISION_MANUAL_REVIEW Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_PASS",
		2: "DECISION_REJECT",
		3: "DECISION_MANUAL_REVIEW",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED":   0,
		"DECISION_PASS":          1,
		"DECISION_REJECT":        2,
		"DECISION_MANUAL_REVIEW": 3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_decision_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_decision_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{0}
}

type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 1
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 2
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 3
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 4
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_LOW",
		2: "RISK_LEVEL_MEDIUM",
		3: "RISK_LEVEL_HIGH",
		4: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_LOW":         1,
		"RISK_LEVEL_MEDIUM":      2,
		"RISK_LEVEL_HIGH":        3,
		"RISK_LEVEL_CRITICAL":    4,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_decision_proto_enumTypes[1].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_decision_proto_enumTypes[1]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{1}
}

// DecisionRequest carries all inputs for a single risk evaluation.
// All scene-specific business data (amount, merchant_id, etc.) is passed via Extra.
type DecisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is a UUID v4; generated by the engine if empty.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SceneCode string `protobuf:"bytes,2,opt,name=scene_code,json=sceneCode,proto3" json:"scene_code,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId  string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ip        string `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	// extra holds all scene-specific key-value pairs.
	// Example: {"amount": "100000", "merchant_id": "M001", "channel": "ALIPAY"}
	Extra         map[string]string `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecisionRequest) GetSceneCode() string {
	if x != nil {
		return x.SceneCode
	}
	return ""
}

func (x *DecisionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DecisionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DecisionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DecisionRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DecisionRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type BatchDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*DecisionRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDecisionRequest) Reset() {
	*x = BatchDecisionRequest{}
	mi := &file_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDecisionRequest) ProtoMessage() {}

func (x *BatchDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDecisionRequest.ProtoReflect.Descriptor instead.
func (*BatchDecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{1}
}

func (x *BatchDecisionRequest) GetRequests() []*DecisionRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// DecisionResponse is the output of a single risk evaluation.
type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Decision      Decision               `protobuf:"varint,2,opt,name=decision,proto3,enum=riskengine.v1.Decision" json:"decision,omitempty"`
	RiskScore     int32                  `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // 0–1000
	RiskLevel     RiskLevel              `protobuf:"varint,4,opt,name=risk_level,json=riskLevel,proto3,enum=riskengine.v1.RiskLevel" json:"risk_level,omitempty"`
	HitRules      []string               `protobuf:"bytes,5,rep,name=hit_rules,json=hitRules,proto3" json:"hit_rules,omitempty"`
	ModelScores   map[string]float64     `protobuf:"bytes,6,rep,name=model_scores,json=modelScores,proto3" json:"model_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	RiskReasons   []string               `protobuf:"bytes,7,rep,name=risk_reasons,json=riskReasons,proto3" json:"risk_reasons,omitempty"`
	Actions       []string               `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	CostMs        int64                  `protobuf:"varint,9,opt,name=cost_ms,json=costMs,proto3" json:"cost_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{2}
}

func (x *DecisionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecisionResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *DecisionResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *DecisionResponse) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *DecisionResponse) GetHitRules() []string {
	if x != nil {
		return x.HitRules
	}
	return nil
}

func (x *DecisionResponse) GetModelScores() map[string]float64 {
	if x != nil {
		return x.ModelScores
	}
	return nil
}

func (x *DecisionResponse) GetRiskReasons() []string {
	if x != nil {
		return x.RiskReasons
	}
	return nil
}

func (x *DecisionResponse) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *DecisionResponse) GetCostMs() int64 {
	if x != nil {
		return x.CostMs
	}
	return 0
}

type BatchDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*DecisionResponse    `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDecisionResponse) Reset() {
	*x = BatchDecisionResponse{}
	mi := &file_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDecisionResponse) ProtoMessage() {}

func (x *BatchDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDecisionResponse.ProtoReflect.Descriptor instead.
func (*BatchDecisionResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{3}
}

func (x *BatchDecisionResponse) GetResponses() []*DecisionResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_decision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Components    map[string]bool        `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_decision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetComponents() map[string]bool {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_decision_proto protoreflect.FileDescriptor

const file_decision_proto_rawDesc = "" +
	"\n" +
	"\x0edecision.proto\x12\rriskengine.v1\"\xc7\x02\n" +
	"\x0fDecisionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"scene_code\x18\x02 \x01(\tR\tsceneCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12?\n" +
	"\x05extra\x18\b \x03(\v2).riskengine.v1.DecisionRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x14BatchDecisionRequest\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.riskengine.v1.DecisionRequestR\brequests\"\xc6\x03\n" +
	"\x10DecisionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x17.riskengine.v1.DecisionR\bdecision\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x05R\triskScore\x127\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\x0e2\x18.riskengine.v1.RiskLevelR\triskLevel\x12\x1b\n" +
	"\thit_rules\x18\x05 \x03(\tR\bhitRules\x12S\n" +
	"\fmodel_scores\x18\x06 \x03(\v20.riskengine.v1.DecisionResponse.ModelScoresEntryR\vmodelScores\x12!\n" +
	"\frisk_reasons\x18\a \x03(\tR\vriskReasons\x12\x18\n" +
	"\aactions\x18\b \x03(\tR\aactions\x12\x17\n" +
	"\acost_ms\x18\t \x01(\x03R\x06costMs\x1a>\n" +
	"\x10ModelScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"V\n" +
	"\x15BatchDecisionResponse\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.riskengine.v1.DecisionResponseR\tresponses\"\x0f\n" +
	"\rHealthRequest\"\xb8\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12M\n" +
	"\n" +
	"components\x18\x02 \x03(\v2-.riskengine.v1.HealthResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01*h\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDECISION_PASS\x10\x01\x12\x13\n" +
	"\x0fDECISION_REJECT\x10\x02\x12\x1a\n" +
	"\x16DECISION_MANUAL_REVIEW\x10\x03*\x80\x01\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x01\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x03\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x042\x81\x02\n" +
	"\x0fDecisionService\x12K\n" +
	"\bEvaluate\x12\x1e.riskengine.v1.DecisionRequest\x1a\x1f.riskengine.v1.DecisionResponse\x12Z\n" +
	"\rBatchEvaluate\x12#.riskengine.v1.BatchDecisionRequest\x1a$.riskengine.v1.BatchDecisionResponse\x12E\n" +
	"\x06Health\x12\x1c.riskengine.v1.HealthRequest\x1a\x1d.riskengine.v1.HealthResponseB2Z0github.com/yourorg/riskengine/api/grpc/v1;riskv1b\x06proto3"

var (
	file_decision_proto_rawDescOnce sync.Once
	file_decision_proto_rawDescData []byte
)

func file_decision_proto_rawDescGZIP() []byte {
	file_decision_proto_rawDescOnce.Do(func() {
		file_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decision_proto_rawDesc), len(file_decision_proto_rawDesc)))
	})
	return file_decision_proto_rawDescData
}

var file_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_decision_proto_goTypes = []any{
	(Decision)(0),                 // 0: riskengine.v1.Decision
	(RiskLevel)(0),                // 1: riskengine.v1.RiskLevel
	(*DecisionRequest)(nil),       // 2: riskengine.v1.DecisionRequest
	(*BatchDecisionRequest)(nil),  // 3: riskengine.v1.BatchDecisionRequest
	(*DecisionResponse)(nil),      // 4: riskengine.v1.DecisionResponse
	(*BatchDecisionResponse)(nil), // 5: riskengine.v1.BatchDecisionResponse
	(*HealthRequest)(nil),         // 6: riskengine.v1.HealthRequest
	(*HealthResponse)(nil),        // 7: riskengine.v1.HealthResponse
	nil,                           // 8: riskengine.v1.DecisionRequest.ExtraEntry
	nil,                           // 9: riskengine.v1.DecisionResponse.ModelScoresEntry
	nil,                           // 10: riskengine.v1.HealthResponse.ComponentsEntry
}
var file_decision_proto_depIdxs = []int32{
	8,  // 0: riskengine.v1.DecisionRequest.extra:type_name -> riskengine.v1.DecisionRequest.ExtraEntry
	2,  // 1: riskengine.v1.BatchDecisionRequest.requests:type_name -> riskengine.v1.DecisionRequest
	0,  // 2: riskengine.v1.DecisionResponse.decision:type_name -> riskengine.v1.Decision
	1,  // 3: riskengine.v1.DecisionResponse.risk_level:type_name -> riskengine.v1.RiskLevel
	9,  // 4: riskengine.v1.DecisionResponse.model_scores:type_name -> riskengine.v1.DecisionResponse.ModelScoresEntry
	4,  // 5: riskengine.v1.BatchDecisionResponse.responses:type_name -> riskengine.v1.DecisionResponse
	10, // 6: riskengine.v1.HealthResponse.components:type_name -> riskengine.v1.HealthResponse.ComponentsEntry
	2,  // 7: riskengine.v1.DecisionService.Evaluate:input_type -> riskengine.v1.DecisionRequest
	3,  // 8: riskengine.v1.DecisionService.BatchEvaluate:input_type -> riskengine.v1.BatchDecisionRequest
	6,  // 9: riskengine.v1.DecisionService.Health:input_type -> riskengine.v1.HealthRequest
	4,  // 10: riskengine.v1.DecisionService.Evaluate:output_type -> riskengine.v1.DecisionResponse
	5,  // 11: riskengine.v1.DecisionService.BatchEvaluate:output_type -> riskengine.v1.BatchDecisionResponse
	7,  // 12: riskengine.v1.DecisionService.Health:output_type -> riskengine.v1.HealthResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_decision_proto_init() }
func file_decision_proto_init() {
	if File_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decision_proto_rawDesc), len(file_decision_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decision_proto_goTypes,
		DependencyIndexes: file_decision_proto_depIdxs,
		EnumInfos:         file_decision_proto_enumTypes,
		MessageInfos:      file_decision_proto_msgTypes,
	}.Build()
	File_decision_proto = out.File
	file_decision_proto_goTypes = nil
	file_decision_proto_depIdxs = nil
}
