// Copyright 2026 RiskEngine Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.4
// source: feature_store.proto

package riskv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeatureStoreService_GetFeatures_FullMethodName      = "/riskengine.v1.FeatureStoreService/GetFeatures"
	FeatureStoreService_BatchGetFeatures_FullMethodName = "/riskengine.v1.FeatureStoreService/BatchGetFeatures"
	FeatureStoreService_Health_FullMethodName           = "/riskengine.v1.FeatureStoreService/Health"
)

// FeatureStoreServiceClient is the client API for FeatureStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FeatureStoreService provides batch feature lookup for the decision engine.
// It is designed to be deployed as a sidecar or standalone microservice.
type FeatureStoreServiceClient interface {
	// GetFeatures fetches a named set of features for a single entity context.
	GetFeatures(ctx context.Context, in *GetFeaturesRequest, opts ...grpc.CallOption) (*GetFeaturesResponse, error)
	// BatchGetFeatures fetches features for multiple entity contexts in one RPC.
	BatchGetFeatures(ctx context.Context, in *BatchGetFeaturesRequest, opts ...grpc.CallOption) (*BatchGetFeaturesResponse, error)
	// Health returns the store's operational status.
	Health(ctx context.Context, in *FeatureStoreHealthRequest, opts ...grpc.CallOption) (*FeatureStoreHealthResponse, error)
}

type featureStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureStoreServiceClient(cc grpc.ClientConnInterface) FeatureStoreServiceClient {
	return &featureStoreServiceClient{cc}
}

func (c *featureStoreServiceClient) GetFeatures(ctx context.Context, in *GetFeaturesRequest, opts ...grpc.CallOption) (*GetFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeaturesResponse)
	err := c.cc.Invoke(ctx, FeatureStoreService_GetFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureStoreServiceClient) BatchGetFeatures(ctx context.Context, in *BatchGetFeaturesRequest, opts ...grpc.CallOption) (*BatchGetFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetFeaturesResponse)
	err := c.cc.Invoke(ctx, FeatureStoreService_BatchGetFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureStoreServiceClient) Health(ctx context.Context, in *FeatureStoreHealthRequest, opts ...grpc.CallOption) (*FeatureStoreHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureStoreHealthResponse)
	err := c.cc.Invoke(ctx, FeatureStoreService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureStoreServiceServer is the server API for FeatureStoreService service.
// All implementations must embed UnimplementedFeatureStoreServiceServer
// for forward compatibility.
//
// FeatureStoreService provides batch feature lookup for the decision engine.
// It is designed to be deployed as a sidecar or standalone microservice.
type FeatureStoreServiceServer interface {
	// GetFeatures fetches a named set of features for a single entity context.
	GetFeatures(context.Context, *GetFeaturesRequest) (*GetFeaturesResponse, error)
	// BatchGetFeatures fetches features for multiple entity contexts in one RPC.
	BatchGetFeatures(context.Context, *BatchGetFeaturesRequest) (*BatchGetFeaturesResponse, error)
	// Health returns the store's operational status.
	Health(context.Context, *FeatureStoreHealthRequest) (*FeatureStoreHealthResponse, error)
	mustEmbedUnimplementedFeatureStoreServiceServer()
}

// UnimplementedFeatureStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeatureStoreServiceServer struct{}

func (UnimplementedFeatureStoreServiceServer) GetFeatures(context.Context, *GetFeaturesRequest) (*GetFeaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatures not implemented")
}
func (UnimplementedFeatureStoreServiceServer) BatchGetFeatures(context.Context, *BatchGetFeaturesRequest) (*BatchGetFeaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetFeatures not implemented")
}
func (UnimplementedFeatureStoreServiceServer) Health(context.Context, *FeatureStoreHealthRequest) (*FeatureStoreHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFeatureStoreServiceServer) mustEmbedUnimplementedFeatureStoreServiceServer() {}
func (UnimplementedFeatureStoreServiceServer) testEmbeddedByValue()                             {}

// UnsafeFeatureStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureStoreServiceServer will
// result in compilation errors.
type UnsafeFeatureStoreServiceServer interface {
	mustEmbedUnimplementedFeatureStoreServiceServer()
}

func RegisterFeatureStoreServiceServer(s grpc.ServiceRegistrar, srv FeatureStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedFeatureStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeatureStoreService_ServiceDesc, srv)
}

func _FeatureStoreService_GetFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureStoreServiceServer).GetFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureStoreService_GetFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureStoreServiceServer).GetFeatures(ctx, req.(*GetFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureStoreService_BatchGetFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureStoreServiceServer).BatchGetFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureStoreService_BatchGetFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureStoreServiceServer).BatchGetFeatures(ctx, req.(*BatchGetFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureStoreService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureStoreHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureStoreServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureStoreService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureStoreServiceServer).Health(ctx, req.(*FeatureStoreHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureStoreService_ServiceDesc is the grpc.ServiceDesc for FeatureStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riskengine.v1.FeatureStoreService",
	HandlerType: (*FeatureStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeatures",
			Handler:    _FeatureStoreService_GetFeatures_Handler,
		},
		{
			MethodName: "BatchGetFeatures",
			Handler:    _FeatureStoreService_BatchGetFeatures_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FeatureStoreService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feature_store.proto",
}
