// Copyright 2026 RiskEngine Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: feature_store.proto

package riskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntityContext carries the identifiers for a decision request.
type EntityContext struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId  string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ip        string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	// extra holds additional entity attributes (e.g. merchant_id, coupon_id).
	Extra         map[string]string `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityContext) Reset() {
	*x = EntityContext{}
	mi := &file_feature_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityContext) ProtoMessage() {}

func (x *EntityContext) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityContext.ProtoReflect.Descriptor instead.
func (*EntityContext) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{0}
}

func (x *EntityContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EntityContext) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EntityContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EntityContext) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EntityContext) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// GetFeaturesRequest asks for a named group of features for one entity.
type GetFeaturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id for tracing (echoed back in response).
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// feature_group identifies which set of features to fetch
	// (e.g. "velocity", "user_profile", "device_risk").
	FeatureGroup  string         `protobuf:"bytes,2,opt,name=feature_group,json=featureGroup,proto3" json:"feature_group,omitempty"`
	Entity        *EntityContext `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesRequest) Reset() {
	*x = GetFeaturesRequest{}
	mi := &file_feature_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesRequest) ProtoMessage() {}

func (x *GetFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesRequest.ProtoReflect.Descriptor instead.
func (*GetFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeaturesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetFeaturesRequest) GetFeatureGroup() string {
	if x != nil {
		return x.FeatureGroup
	}
	return ""
}

func (x *GetFeaturesRequest) GetEntity() *EntityContext {
	if x != nil {
		return x.Entity
	}
	return nil
}

// FeatureValue is a tagged union for feature values.
type FeatureValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FeatureValue_IntVal
	//	*FeatureValue_FloatVal
	//	*FeatureValue_StringVal
	//	*FeatureValue_BoolVal
	Value         isFeatureValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureValue) Reset() {
	*x = FeatureValue{}
	mi := &file_feature_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureValue) ProtoMessage() {}

func (x *FeatureValue) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureValue.ProtoReflect.Descriptor instead.
func (*FeatureValue) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureValue) GetValue() isFeatureValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FeatureValue) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *FeatureValue) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *FeatureValue) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *FeatureValue) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

type isFeatureValue_Value interface {
	isFeatureValue_Value()
}

type FeatureValue_IntVal struct {
	IntVal int64 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type FeatureValue_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,2,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type FeatureValue_StringVal struct {
	StringVal string `protobuf:"bytes,3,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type FeatureValue_BoolVal struct {
	BoolVal bool `protobuf:"varint,4,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

func (*FeatureValue_IntVal) isFeatureValue_Value() {}

func (*FeatureValue_FloatVal) isFeatureValue_Value() {}

func (*FeatureValue_StringVal) isFeatureValue_Value() {}

func (*FeatureValue_BoolVal) isFeatureValue_Value() {}

// GetFeaturesResponse returns a named map of feature values.
type GetFeaturesResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FeatureGroup string                 `protobuf:"bytes,2,opt,name=feature_group,json=featureGroup,proto3" json:"feature_group,omitempty"`
	// features maps feature key → value.
	Features map[string]*FeatureValue `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// missing_keys lists keys that were requested but had no data.
	MissingKeys []string `protobuf:"bytes,4,rep,name=missing_keys,json=missingKeys,proto3" json:"missing_keys,omitempty"`
	// fetch_ms is the server-side computation latency.
	FetchMs       int64 `protobuf:"varint,5,opt,name=fetch_ms,json=fetchMs,proto3" json:"fetch_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeaturesResponse) Reset() {
	*x = GetFeaturesResponse{}
	mi := &file_feature_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturesResponse) ProtoMessage() {}

func (x *GetFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturesResponse.ProtoReflect.Descriptor instead.
func (*GetFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeaturesResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetFeaturesResponse) GetFeatureGroup() string {
	if x != nil {
		return x.FeatureGroup
	}
	return ""
}

func (x *GetFeaturesResponse) GetFeatures() map[string]*FeatureValue {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetFeaturesResponse) GetMissingKeys() []string {
	if x != nil {
		return x.MissingKeys
	}
	return nil
}

func (x *GetFeaturesResponse) GetFetchMs() int64 {
	if x != nil {
		return x.FetchMs
	}
	return 0
}

// BatchGetFeaturesRequest bundles multiple GetFeaturesRequests.
type BatchGetFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*GetFeaturesRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFeaturesRequest) Reset() {
	*x = BatchGetFeaturesRequest{}
	mi := &file_feature_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFeaturesRequest) ProtoMessage() {}

func (x *BatchGetFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFeaturesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetFeaturesRequest) GetRequests() []*GetFeaturesRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// BatchGetFeaturesResponse bundles the corresponding responses.
type BatchGetFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*GetFeaturesResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFeaturesResponse) Reset() {
	*x = BatchGetFeaturesResponse{}
	mi := &file_feature_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFeaturesResponse) ProtoMessage() {}

func (x *BatchGetFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFeaturesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetFeaturesResponse) GetResponses() []*GetFeaturesResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type FeatureStoreHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureStoreHealthRequest) Reset() {
	*x = FeatureStoreHealthRequest{}
	mi := &file_feature_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureStoreHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureStoreHealthRequest) ProtoMessage() {}

func (x *FeatureStoreHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureStoreHealthRequest.ProtoReflect.Descriptor instead.
func (*FeatureStoreHealthRequest) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{6}
}

type FeatureStoreHealthResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Healthy bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// backend_statuses maps backend name → healthy.
	BackendStatuses map[string]bool `protobuf:"bytes,3,rep,name=backend_statuses,json=backendStatuses,proto3" json:"backend_statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FeatureStoreHealthResponse) Reset() {
	*x = FeatureStoreHealthResponse{}
	mi := &file_feature_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureStoreHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureStoreHealthResponse) ProtoMessage() {}

func (x *FeatureStoreHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureStoreHealthResponse.ProtoReflect.Descriptor instead.
func (*FeatureStoreHealthResponse) Descriptor() ([]byte, []int) {
	return file_feature_store_proto_rawDescGZIP(), []int{7}
}

func (x *FeatureStoreHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *FeatureStoreHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FeatureStoreHealthResponse) GetBackendStatuses() map[string]bool {
	if x != nil {
		return x.BackendStatuses
	}
	return nil
}

var File_feature_store_proto protoreflect.FileDescriptor

const file_feature_store_proto_rawDesc = "" +
	"\n" +
	"\x13feature_store.proto\x12\rriskengine.v1\"\xed\x01\n" +
	"\rEntityContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12=\n" +
	"\x05extra\x18\x05 \x03(\v2'.riskengine.v1.EntityContext.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x12GetFeaturesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rfeature_group\x18\x02 \x01(\tR\ffeatureGroup\x124\n" +
	"\x06entity\x18\x03 \x01(\v2\x1c.riskengine.v1.EntityContextR\x06entity\"\x8f\x01\n" +
	"\fFeatureValue\x12\x19\n" +
	"\aint_val\x18\x01 \x01(\x03H\x00R\x06intVal\x12\x1d\n" +
	"\tfloat_val\x18\x02 \x01(\x01H\x00R\bfloatVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\x03 \x01(\tH\x00R\tstringVal\x12\x1b\n" +
	"\bbool_val\x18\x04 \x01(\bH\x00R\aboolValB\a\n" +
	"\x05value\"\xbf\x02\n" +
	"\x13GetFeaturesResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rfeature_group\x18\x02 \x01(\tR\ffeatureGroup\x12L\n" +
	"\bfeatures\x18\x03 \x03(\v20.riskengine.v1.GetFeaturesResponse.FeaturesEntryR\bfeatures\x12!\n" +
	"\fmissing_keys\x18\x04 \x03(\tR\vmissingKeys\x12\x19\n" +
	"\bfetch_ms\x18\x05 \x01(\x03R\afetchMs\x1aX\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.riskengine.v1.FeatureValueR\x05value:\x028\x01\"X\n" +
	"\x17BatchGetFeaturesRequest\x12=\n" +
	"\brequests\x18\x01 \x03(\v2!.riskengine.v1.GetFeaturesRequestR\brequests\"\\\n" +
	"\x18BatchGetFeaturesResponse\x12@\n" +
	"\tresponses\x18\x01 \x03(\v2\".riskengine.v1.GetFeaturesResponseR\tresponses\"\x1b\n" +
	"\x19FeatureStoreHealthRequest\"\xff\x01\n" +
	"\x1aFeatureStoreHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12i\n" +
	"\x10backend_statuses\x18\x03 \x03(\v2>.riskengine.v1.FeatureStoreHealthResponse.BackendStatusesEntryR\x0fbackendStatuses\x1aB\n" +
	"\x14BackendStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xaf\x02\n" +
	"\x13FeatureStoreService\x12T\n" +
	"\vGetFeatures\x12!.riskengine.v1.GetFeaturesRequest\x1a\".riskengine.v1.GetFeaturesResponse\x12c\n" +
	"\x10BatchGetFeatures\x12&.riskengine.v1.BatchGetFeaturesRequest\x1a'.riskengine.v1.BatchGetFeaturesResponse\x12]\n" +
	"\x06Health\x12(.riskengine.v1.FeatureStoreHealthRequest\x1a).riskengine.v1.FeatureStoreHealthResponseB2Z0github.com/yourorg/riskengine/api/grpc/v1;riskv1b\x06proto3"

var (
	file_feature_store_proto_rawDescOnce sync.Once
	file_feature_store_proto_rawDescData []byte
)

func file_feature_store_proto_rawDescGZIP() []byte {
	file_feature_store_proto_rawDescOnce.Do(func() {
		file_feature_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feature_store_proto_rawDesc), len(file_feature_store_proto_rawDesc)))
	})
	return file_feature_store_proto_rawDescData
}

var file_feature_store_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_feature_store_proto_goTypes = []any{
	(*EntityContext)(nil),              // 0: riskengine.v1.EntityContext
	(*GetFeaturesRequest)(nil),         // 1: riskengine.v1.GetFeaturesRequest
	(*FeatureValue)(nil),               // 2: riskengine.v1.FeatureValue
	(*GetFeaturesResponse)(nil),        // 3: riskengine.v1.GetFeaturesResponse
	(*BatchGetFeaturesRequest)(nil),    // 4: riskengine.v1.BatchGetFeaturesRequest
	(*BatchGetFeaturesResponse)(nil),   // 5: riskengine.v1.BatchGetFeaturesResponse
	(*FeatureStoreHealthRequest)(nil),  // 6: riskengine.v1.FeatureStoreHealthRequest
	(*FeatureStoreHealthResponse)(nil), // 7: riskengine.v1.FeatureStoreHealthResponse
	nil,                                // 8: riskengine.v1.EntityContext.ExtraEntry
	nil,                                // 9: riskengine.v1.GetFeaturesResponse.FeaturesEntry
	nil,                                // 10: riskengine.v1.FeatureStoreHealthResponse.BackendStatusesEntry
}
var file_feature_store_proto_depIdxs = []int32{
	8,  // 0: riskengine.v1.EntityContext.extra:type_name -> riskengine.v1.EntityContext.ExtraEntry
	0,  // 1: riskengine.v1.GetFeaturesRequest.entity:type_name -> riskengine.v1.EntityContext
	9,  // 2: riskengine.v1.GetFeaturesResponse.features:type_name -> riskengine.v1.GetFeaturesResponse.FeaturesEntry
	1,  // 3: riskengine.v1.BatchGetFeaturesRequest.requests:type_name -> riskengine.v1.GetFeaturesRequest
	3,  // 4: riskengine.v1.BatchGetFeaturesResponse.responses:type_name -> riskengine.v1.GetFeaturesResponse
	10, // 5: riskengine.v1.FeatureStoreHealthResponse.backend_statuses:type_name -> riskengine.v1.FeatureStoreHealthResponse.BackendStatusesEntry
	2,  // 6: riskengine.v1.GetFeaturesResponse.FeaturesEntry.value:type_name -> riskengine.v1.FeatureValue
	1,  // 7: riskengine.v1.FeatureStoreService.GetFeatures:input_type -> riskengine.v1.GetFeaturesRequest
	4,  // 8: riskengine.v1.FeatureStoreService.BatchGetFeatures:input_type -> riskengine.v1.BatchGetFeaturesRequest
	6,  // 9: riskengine.v1.FeatureStoreService.Health:input_type -> riskengine.v1.FeatureStoreHealthRequest
	3,  // 10: riskengine.v1.FeatureStoreService.GetFeatures:output_type -> riskengine.v1.GetFeaturesResponse
	5,  // 11: riskengine.v1.FeatureStoreService.BatchGetFeatures:output_type -> riskengine.v1.BatchGetFeaturesResponse
	7,  // 12: riskengine.v1.FeatureStoreService.Health:output_type -> riskengine.v1.FeatureStoreHealthResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_feature_store_proto_init() }
func file_feature_store_proto_init() {
	if File_feature_store_proto != nil {
		return
	}
	file_feature_store_proto_msgTypes[2].OneofWrappers = []any{
		(*FeatureValue_IntVal)(nil),
		(*FeatureValue_FloatVal)(nil),
		(*FeatureValue_StringVal)(nil),
		(*FeatureValue_BoolVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feature_store_proto_rawDesc), len(file_feature_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feature_store_proto_goTypes,
		DependencyIndexes: file_feature_store_proto_depIdxs,
		MessageInfos:      file_feature_store_proto_msgTypes,
	}.Build()
	File_feature_store_proto = out.File
	file_feature_store_proto_goTypes = nil
	file_feature_store_proto_depIdxs = nil
}
